TEMP/Models/License.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public License()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int id { get; set; }
        public Nullable<int> licenseType { get; set; }
        public Nullable<int> licenseDuration { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> customerID { get; set; }
        public Nullable<System.DateTime> nextTransactionDate { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public int PlanID { get; set; }
        public string SaleRepResponsible { get; set; }
        public string LicenseKey { get; set; }
        public string LinkUse { get; set; }
        public string AdminAccount { get; set; }
        public string AdminPassword { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual customer customer { get; set; }
        public virtual productMarketPlan productMarketPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}

TEMP/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace SSM.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

TEMP/Controllers/LicenseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SSM.Controllers
{
    [Authorize]
    public class LicenseController : iController
    {
        // GET: License
        public ActionResult Index()
        {
            ViewData["licenseList"] = dbcnt.Licenses.ToList();
            return View("Manage");
        }
        public ActionResult licenseDetail(int id) {
            return View("LicenseDetil");
        }
    }
}

TEMP/Controllers/ManageController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SSM.Models;
using System.Configuration;

namespace SSM.Controllers
{
    [Authorize]
    public class ManageController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ManageController()
        {
        }

        public ManageController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }
        public ActionResult SystemConfig() {
            SSMEntities se = new SSMEntities();
            ViewData["email"] = se.ConfigureSys.Find(1).value;
            ViewData["sc"] = se.ConfigureSys.Find(15).value;
            ViewData["act"] = se.ConfigureSys.Find(16).value;
            ViewData["ncm"] = se.ConfigureSys.Find(17).value;
            ViewData["wr"] = se.ConfigureSys.Find(19).value;
            ViewData["asv"] = se.ConfigureSys.Find(20).value;
            ViewData["fn"] = se.ConfigureSys.Find(3).value;
            ViewData["pn"] = se.ConfigureSys.Find(4).value;
            ViewData["mdd"] = se.ConfigureSys.Find(5).value;
            ViewData["mt"] = se.ConfigureSys.Find(7).value;
            ViewData["lk"] = se.ConfigureSys.Find(8).value;
            ViewData["news"] = se.ConfigureSys.Find(9).value;
            ViewData["pf"] = se.ConfigureSys.Find(10).value;
            ViewData["cc"] = se.ConfigureSys.Find(11).value;
            ViewData["links"] = se.ConfigureSys.Find(12).value;
            ViewData["username"] = se.ConfigureSys.Find(13).value;
            ViewData["password"] = se.ConfigureSys.Find(14).value;
   
            return View("SystemConfig");
        }
        public ActionResult UdpateMetric(int sc, int act, int ncm, int wr, int asv)
        {

            SSMEntities se = new SSMEntities();
            se.ConfigureSys.Where(u => u.id == 15).First().value = sc+ "";
            se.ConfigureSys.Where(u => u.id == 16).First().value = act + "";
            se.ConfigureSys.Where(u => u.id == 17).First().value = ncm + "";
            se.ConfigureSys.Where(u => u.id == 19).First().value = wr + "";
            se.ConfigureSys.Where(u => u.id == 20).First().value = asv + "";
            se.SaveChanges();
            return RedirectToAction("SystemConfig");
        }
        public ActionResult UpdateKeyword(String fn, string pn, string mdd, string mt, string lk,string news, string pf, string cc, string links, string username, string password)
        {
            SSMEntities se = new SSMEntities();
            se.ConfigureSys.Where(u => u.id == 3).First().value = fn + "";
            se.ConfigureSys.Where(u => u.id == 4).First().value = pn + "";
            se.ConfigureSys.Where(u => u.id == 5).First().value = mdd + "";
            se.ConfigureSys.Where(u => u.id == 7).First().value = mt + "";
            se.ConfigureSys.Where(u => u.id == 8).First().value = lk + "";
            se.ConfigureSys.Where(u => u.id == 9).First().value = news + "";
            se.ConfigureSys.Where(u => u.id == 10).First().value = pf + "";
            se.ConfigureSys.Where(u => u.id == 11).First().value = cc + "";
            se.ConfigureSys.Where(u => u.id == 12).First().value = links + "";
            se.ConfigureSys.Where(u => u.id ==13).First().value = username + "";
            se.ConfigureSys.Where(u => u.id == 14).First().value = password + "";

            se.SaveChanges();

            return RedirectToAction("SystemConfig");
        }
        public ActionResult UpdateMail(string username,string password)
        {
            SSMEntities se = new SSMEntities();
            se.ConfigureSys.Where(u => u.id == 1).First().value = username + "";
            se.ConfigureSys.Where(u => u.id == 2).First().value = password + "";
            se.SaveChanges();
            return RedirectToAction("SystemConfig");
        }
        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set 
            { 
                _signInManager = value; 
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Manage/Index
        public async Task<ActionResult> Index(ManageMessageId? message)
        {
            ViewBag.StatusMessage =
                message == ManageMessageId.ChangePasswordSuccess ? "Your password has been changed."
                : message == ManageMessageId.SetPasswordSuccess ? "Your password has been set."
                : message == ManageMessageId.SetTwoFactorSuccess ? "Your two-factor authentication provider has been set."
                : message == ManageMessageId.Error ? "An error has occurred."
                : message == ManageMessageId.AddPhoneSuccess ? "Your phone number was added."
                : message == ManageMessageId.RemovePhoneSuccess ? "Your phone number was removed."
                : "";

            var userId = User.Identity.GetUserId();
            var model = new IndexViewModel
            {
                HasPassword = HasPassword(),
                PhoneNumber = await UserManager.GetPhoneNumberAsync(userId),
                TwoFactor = await UserManager.GetTwoFactorEnabledAsync(userId),
                Logins = await UserManager.GetLoginsAsync(userId),
                BrowserRemembered = await AuthenticationManager.TwoFactorBrowserRememberedAsync(userId)
            };
            return View(model);
        }

        //
        // POST: /Manage/RemoveLogin
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> RemoveLogin(string loginProvider, string providerKey)
        {
            ManageMessageId? message;
            var result = await UserManager.RemoveLoginAsync(User.Identity.GetUserId(), new UserLoginInfo(loginProvider, providerKey));
            if (result.Succeeded)
            {
                var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
                if (user != null)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
                }
                message = ManageMessageId.RemoveLoginSuccess;
            }
            else
            {
                message = ManageMessageId.Error;
            }
            return RedirectToAction("ManageLogins", new { Message = message });
        }

        //
        // GET: /Manage/AddPhoneNumber
        public ActionResult AddPhoneNumber()
        {
            return View();
        }

        //
        // POST: /Manage/AddPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddPhoneNumber(AddPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            // Generate the token and send it
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), model.Number);
            if (UserManager.SmsService != null)
            {
                var message = new IdentityMessage
                {
                    Destination = model.Number,
                    Body = "Your security code is: " + code
                };
                await UserManager.SmsService.SendAsync(message);
            }
            return RedirectToAction("VerifyPhoneNumber", new { PhoneNumber = model.Number });
        }

        //
        // POST: /Manage/EnableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EnableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), true);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // POST: /Manage/DisableTwoFactorAuthentication
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DisableTwoFactorAuthentication()
        {
            await UserManager.SetTwoFactorEnabledAsync(User.Identity.GetUserId(), false);
            var user = await UserManager.FindByIdAsync(User.Identity.GetUserId());
            if (user != null)
            {
                await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);
            }
            return RedirectToAction("Index", "Manage");
        }

        //
        // GET: /Manage/VerifyPhoneNumber
        public async Task<ActionResult> VerifyPhoneNumber(string phoneNumber)
        {
            var code = await UserManager.GenerateChangePhoneNumberTokenAsync(User.Identity.GetUserId(), phoneNumber);
            // Send an SMS through the SMS provider to verify the phone number
            return phoneNumber == null ? View("Error") : View(new VerifyPhoneNumberViewModel { PhoneNumber = phoneNumber });
        }

        //
        // POST: /Manage/VerifyPhoneNumber
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyPhoneNumber(VerifyPhoneNumberViewModel model)
        {
            if (!ModelState.IsValid)
            {

TEMP/Views/License/LicenseDetil.cshtml
@{
    ViewBag.Title = "LicenseDetil";
}
<style type="text/css">
    @@font-face {
        font-family: 'Roboto-Light';
        src: url("../../fonts/Roboto-Light.ttf") format('truetype');
    }

    @@font-face {
        font-family: 'Roboto-Black';
        src: url("../../fonts/Roboto-Black.ttf") format('truetype');
    }
    th, td {
    border-bottom: 1px solid #ddd;
}
    body {
    font-family:Roboto-Light
    }
</style>


<h1> <font style="font-family:Roboto-Light"> License Detail</font> </h1>

<table width="50%">
    <tr>
        <td colspan="2">
            <h4> <font style="font-family:Roboto-Black"> User detail</font> </h4>
        </td>
       
    </tr>
    <tr>
        <td>
            Customer Status
        </td>
        <td>
            Active
        </td>
    </tr>
    <tr>
        <td>
            License Plan
        </td>
        <td>
            Monthly Payment
        </td>
    </tr>
    <tr>
        <td>
           
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td colspan="2">
            <h4> <font style="font-family:Roboto-Black"> Plan detail</font> </h4>
        </td>

    </tr>
    <tr>
        <td>
            Plan
        </td>
        <td>
            Montly Payment
        </td>
    </tr>
    <tr>
        <td>
            Users
        </td>
        <td>
            9
        </td>
    </tr>
    <tr>
        <td>
            Account Available
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td colspan="2">
            <h4> <font style="font-family:Roboto-Black"> Transaction detail</font> </h4>
        </td>

    </tr>
    <tr>
        <td>
            StartDate
        </td>
        <td>
            9/7/2016
        </td>
    </tr>
    <tr>
        <td>
            Next Transaction Date
        </td>
        <td>
            10/7/2016
        </td>
    </tr>
    <tr>
        <td>
           Total payment
        </td>
        <td>
            $200.00
        </td>
    </tr>
</table>

TEMP/Views/License/Manage.cshtml
@using SSM.Models;
<style type="text/css">
    @@font-face {
        font-family: 'Roboto-Light';
        src: url("../../fonts/Roboto-Light.ttf") format('truetype');
    }

    @@font-face {
        font-family: 'Roboto-Black';
        src: url("../../fonts/Roboto-Black.ttf") format('truetype');
    }
</style>

<link href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css" rel="stylesheet" />

<script src="//code.jquery.com/jquery-1.12.3.js"> </script>
<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"> </script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"> </script>


<script>
    $(document).ready(function () {
        $('#datatableExaple').DataTable();
    });
</script>

<h1> <font style="font-family:Roboto-Light">Licenses Listing</font> </h1>
<table id="datatableExaple" class="table table-striped table-bordered" cellspacing="0">
    <thead>
        <tr>
            <th>Customer name</th>
            <th>Customer Email</th>
            <th>Service</th>
            <th>Plan</th>
            <th>Total Revenue</th>
            <th>Detail</th>
        </tr>
    </thead>

    <tbody>
        @if (ViewData["licenseList"] != null)
        {
            foreach (License lc in (List<License>)ViewData["licenseList"])
            {
                <tr>
                    <td>
                        @lc.customer.cusName
                    </td>
                    <td>
                        @lc.customer.cusEmail
                    </td>
                    <td>
                        @lc.softwareProduct.name
                    </td>
                    <td>
                        @lc.licenseType
                    </td>
                    <td>
                        Total Revenue
                    </td>
                    <td>
                        @using (Html.BeginForm("licenseDetail", "License"))
                        {
                            <input type="hidden" value="@lc.id" name="id" />


                            <button type="submit"> Detail </button>
                        }


                    </td>
                </tr>
            }
        }
    </tbody>
</table>