TEMP/Models/Deal.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.Customer_Request = new HashSet<Customer_Request>();
            this.Deal_Item = new HashSet<Deal_Item>();
            this.Deal_SaleRep_Respon = new HashSet<Deal_SaleRep_Respon>();
            this.orders = new HashSet<order>();
            this.DealTasks = new HashSet<DealTask>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public int Stage { get; set; }
        public Nullable<double> Value { get; set; }
        public Nullable<double> Probability { get; set; }
        public string Creator { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> CompleteOn { get; set; }
        public int Client { get; set; }
        public Nullable<System.DateTime> LastUpdateStage { get; set; }
        public Nullable<int> Status { get; set; }
        public int ProductID { get; set; }
        public int CurrentPlanID { get; set; }
    
        public virtual contact contact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Request> Customer_Request { get; set; }
        public virtual DealStatu DealStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_Item> Deal_Item { get; set; }
        public virtual PrePurchase_FollowUp_Plan PrePurchase_FollowUp_Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deal_SaleRep_Respon> Deal_SaleRep_Respon { get; set; }
        public virtual softwareProduct softwareProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DealTask> DealTasks { get; set; }
    }
}

TEMP/Controllers/DealController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SSM.Models;
using Microsoft.AspNet.Identity;
using Hangfire;
using SSM.Models.Services;
using SSM.Models.Repository;
using SSM.Models.Storage;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Threading.Tasks;

namespace SSM.Controllers
{
    [Authorize]
    public class DealController : Controller
    {
        // GET: Deal
        public ActionResult Index()
        {
            SSMEntities se = new SSMEntities();
            AspNetUser thisUSer = se.AspNetUsers.Find(User.Identity.GetUserId());
            if (thisUSer != null) {
                if (User.IsInRole("manager")) {
                    ViewData["ActiveDeal"] = se.Deals.OrderBy(u => u.Status).ToList();

                }
                else
                {
                    ViewData["ActiveDeal"] = thisUSer.Deal_SaleRep_Respon.Select(u => u.Deal).OrderBy(u => u.Status).ToList();
                }
            }

            return View("");
        }
        public ActionResult CreateDeal(Deal deal, int productID, int chooseplan)
        {
            int id = createAndGetDealID(deal, productID, chooseplan);

            return RedirectToAction("Detail", new { id = id });

        }
        [ValidateInput(false)]
        public ActionResult NewEmail(String mailcontent, int dealID)
        {
            SSMEntities se = new SSMEntities();
            Deal deal = se.Deals.Find(dealID);
            if (deal != null)
            {
                DealTask task = new Models.DealTask();
                task.type = 8;
                task.TaskName = deal.DealTasks.Where(u => u.type == 8).First().TaskName;
                task.status = 1;
                task.Deadline = DateTime.Now;
                task.CreateDate = DateTime.Now;
                task.TaskDescription = mailcontent;
                task.dealID = dealID;
                task.TaskContent = "ReplyEmail";
                se.DealTasks.Add(task);
                se.SaveChanges();
            }
            return RedirectToAction("Detail", new { id = dealID });

        }

        public int createAndGetDealID(Deal deal, int productID,int plann)
        {
            SSMEntities se = new SSMEntities();
            softwareProduct product = se.softwareProducts.Find(productID);
            if (product != null) deal.ProductID = productID;
            deal.Creator = User.Identity.GetUserId();
            deal.StartDate = DateTime.Today;
            deal.Stage = 1;
            deal.Probability = 0;
            deal.CompleteOn = null;
            deal.LastUpdateStage = null;
            deal.Status = 1;
            deal.CurrentPlanID = product.PrePurchase_FollowUp_Plan.Where(u => u.isOperation).FirstOrDefault().id;

            se.Deals.Add(deal);
            se.SaveChanges();
            Deal_Item ite = new Deal_Item();
            productMarketPlan pla = se.productMarketPlans.Find(plann);
            ite.planID = plann;
            ite.price = pla.ceilPrice;
            ite.Quantity = 1;
            ite.dealID = deal.id;
            se.Deal_Item.Add(ite);
            deal.Value = ite.price;
            se.SaveChanges();
            Deal_SaleRep_Respon dealrespont = new Deal_SaleRep_Respon();
            dealrespont.dealID = deal.id;
            dealrespont.userID = deal.Creator;
            se.Deal_SaleRep_Respon.Add(dealrespont);
            se.SaveChanges();
            contact contact = se.contacts.Find(deal.Client);
            int day = 0;
            PrePurchase_FollowUp_Plan plan = deal.softwareProduct.PrePurchase_FollowUp_Plan.Where(u => u.isOperation == true).FirstOrDefault();
            if (contact != null)
            {
                foreach (Plan_Step tep in plan.Plan_Step)
                {

                    if (tep.TimeFromLastStep == null) tep.TimeFromLastStep = 0;
                    day = day + (int)tep.TimeFromLastStep;
                    DealTask task = new DealTask();
                    task.dealID = deal.id;
                    task.TaskDescription = tep.StepEmailContent;
                    task.status = 1;
                    if (tep.RequireMoreDetail) task.status = 7;
                    task.Deadline = DateTime.Now.AddDays(day);
                    task.CreateDate = DateTime.Now;
                    task.TaskContent = tep.stepNo + "";
                    task.TaskName = tep.subject + " [#:" + deal.id + "]";
                    task.type = 8;
                    se.DealTasks.Add(task);
                    se.SaveChanges();
                    if (task.TaskDescription.Contains(se.ConfigureSys.Find(13).value))
                    {
                        String replaceall = "";
                        foreach (Deal_Item item in task.Deal.Deal_Item)
                        {
                            TrialAccount trial = item.productMarketPlan.TrialAccounts.Where(u => u.contactID == null).FirstOrDefault();
                            replaceall = replaceall + '\n' + "User Name for " + item.productMarketPlan.Name + ": " + trial.UserName + " Password: " + trial.Password;
                            TrialAccount trialupdate = se.TrialAccounts.Find(trial.AccountID);
                            trialupdate.contactID = task.Deal.contact.id;
                            se.SaveChanges();
                        }
                        task.TaskDescription = task.TaskDescription.Replace(se.ConfigureSys.Find(13).value, replaceall);
                    }
                    se.SaveChanges();
                }
            }


            return deal.id;

        }
        public JsonResult removeEmail(int mailid) {
            SSMEntities se = new SSMEntities();
            DealTask task = se.DealTasks.Find(mailid);
            if (task != null)
            {
                try {
                    
             
                    foreach (DealTask alltask in task.Deal.DealTasks.Where(u => u.type == 8 && u.Deadline > task.Deadline).ToList()) {
                        alltask.TaskContent = (int.Parse(alltask.TaskContent) - 1) +"";
                    }
                    se.DealTasks.Remove(task);
                    se.SaveChanges();
                    return Json(new { sentresult = "succeed" }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception e) {

                }
            }
            
            return Json(new { sentresult = "fail" }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult SendEarlyMail(int mailid) {
            SSMEntities se = new SSMEntities();
            DealTask task = se.DealTasks.Find(mailid);
            if (task != null) {
                if (task.Deal.Stage +1< (int.Parse(task.TaskContent)))
                {
                    return Json(new { sentresult = "fail" }, JsonRequestBehavior.AllowGet);
                }
                else {
                    task.Deadline = DateTime.Now;
                    se.SaveChanges();
                    return Json(new { sentresult = "suceed" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { sentresult = "fail" }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult AddItemToDeal(int planID, float suggestprice, int quantity, int dealID)
        {
            SSMEntities se = new SSMEntities();
            Deal deal = se.Deals.Find(dealID);
            if (deal != null)
            {
                Deal_Item item = new Deal_Item();
                item.planID = planID;
                item.dealID = dealID;
                item.price = suggestprice;
                item.Quantity = quantity;
                if (deal.Value == null)
                    deal.Value = suggestprice * quantity;
                else
                    deal.Value = deal.Value + suggestprice * quantity;
                se.Deal_Item.Add(item);
                se.SaveChanges();
            }
            return RedirectToAction("Detail", new { id = dealID });

        }
        public JsonResult getPlanMinMax(int planID)
        {
            SSMEntities se = new SSMEntities();
            productMarketPlan plan = se.productMarketPlans.Find(planID);
            if (plan != null)
            {
                return Json(new { min = plan.floorprice, max = plan.ceilPrice }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { result = "fail" }, JsonRequestBehavior.AllowGet);

        }
        public ActionResult Detail(int id)
        {
            SSMEntities se = new SSMEntities();
            Deal thisDeal = se.Deals.Find(id);
            try
            {

                ViewData["DealDetail"] = thisDeal;

                List<SelectListItem> productPlan = new List<SelectListItem>();
                foreach (productMarketPlan plan in thisDeal.softwareProduct.productMarketPlans.ToList())
                {
                    productPlan.Add(new SelectListItem() { Text = plan.Name, Value = plan.id + "" });
                }

                ViewData["PlanList"] = productPlan;
                ViewData["TaskStatus"] = se.TaskStatus.ToList();
                ViewData["TaskTypes"] = se.TaskTypes.ToList();



                softwareProduct thisproduct = thisDeal.softwareProduct;
                int days = 0;
                foreach (PrePurchase_FollowUp_Plan plan in thisproduct.PrePurchase_FollowUp_Plan.ToList())
                {
                    if (plan.isOperation)
                    {
                        foreach (Plan_Step step in plan.Plan_Step)
                        {
                            if (step.TimeFromLastStep != null) days = days + (int)step.TimeFromLastStep;
                        }
                    }

                }
                System.Diagnostics.Debug.WriteLine("AAAAAAAAAAA " + days + " BBBBBB " + (DateTime.Today - thisDeal.StartDate).Days);

TEMP/Views/Deal/Create.cshtml
@model SSM.Models.Deal
@using SSM.Models
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">




</head>


@using (Html.BeginForm("CreateDeal", "Deal", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Deal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Client, "Client", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Client", (List<SelectListItem>)ViewData["ClientResponsibleFor"], htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Client, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Prroduct</label>
            <div class="col-md-10">
                @Html.DropDownList("productID", (List<SelectListItem>)ViewData["ProductResponsibleFor"], htmlAttributes: new { @class = "form-control" })

            </div>
        </div>
       <input type="hidden" value="" name="chooseplan" id="chooseplan"/>
        <div class="form-group">
            <label class="control-label col-md-2">Plan</label>
            <div class="col-md-10">
                @Html.DropDownList("PlanToChoose", new List<SelectListItem>(), htmlAttributes: new { @class = "form-control" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

    foreach (productMarketPlan plan in (List<productMarketPlan>)ViewData["ProductPlan"])
    {
        <script>
            $("#PlanToChoose").append('<option class="productplan product@(plan.softwareProduct.id)" value="@(plan.id)">@(plan.Name)</option>');
        </script>
    }
    <script>
      
        var pid = "";
        function displayplan() {
            if (pid != $("#productID").val()) {
                pid = $("#productID").val();
                $(".productplan").each(function () {
                    $(this).css("display", "none");
                })
                $(".product" + pid).each(function () {
                    $(this).css("display", "");
                })
                
            }
        }
        alert($("#PlanToChoose").val());
        function updateval() {
            $("#chooseplan").val($("#PlanToChoose").val());
        }
        setInterval(displayplan, 100);
        setInterval(updateval, 100);
    </script>

}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TEMP/Views/Deal/index.cshtml
@using SSM.Models;

<link href="~/Content/fonts/css/font-awesome.min.css" rel="stylesheet" />
<link href="~/Content/animate.min.css" rel="stylesheet" />
<link href="~/Content/custom.css" rel="stylesheet" />
<link href="~/Content/icheck/flat/green.css" rel="stylesheet" />
<style>
    body {
    background-color:#F7F7F7;
    }
</style>

<script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"> </script>
<script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"> </script>

<script>
    $(document).ready(function () {
        $("#dealtable").DataTable({
            "order": [[4, "desc"]]
        });
    })
</script>
    <div class="page-title">
        <div class="title_left">
            <h1 style="font-size:30px">Deals <small> Listing</small></h1>
        </div>
        <div class="title_right">
            <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Go!</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel">
 
                <div class="x_content">
                    <p>List of deals under your responsible</p>
                    <!-- start project list -->
                    <table id="dealtable" class="table table-striped projects">
                        <thead>
                            <tr>
                     
                                <th style="width: 20%">Deal name</th>
                                <th>Created</th>
                                <th>Deal Progress</th>
                                <th>Status</th>
                                <th style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                  
                            @foreach (Deal deal in (List<Deal>)ViewData["ActiveDeal"])
                            {
                                <tr>
                              
                                    <td>
                                        <a>@deal.Name</a>
                                        <br />
                                        <small>@deal.contact.FirstName @deal.contact.MiddleName @deal.contact.LastName </small>
                                    </td>
                                    <td>@deal.StartDate.ToShortDateString()</td>
                                    <td class="project_progress">
                                        <div class="progress progress_sm">
                                            <div class="progress-bar bg-green" role="progressbar" data-transitiongoal="@(deal.Stage * 100 / (deal.softwareProduct.PrePurchase_FollowUp_Plan.Where(u => u.isOperation).First().Plan_Step.ToList().Count()))" style="width: @(deal.Stage * 100 / (deal.softwareProduct.PrePurchase_FollowUp_Plan.Where(u => u.isOperation).First().Plan_Step.ToList().Count()))%;"></div>
                                        </div>
                                      
                                        <small>@(deal.Stage * 100 / (deal.softwareProduct.PrePurchase_FollowUp_Plan.Where(u => u.isOperation).First().Plan_Step.ToList().Count()))% Complete</small>
                                    </td>
                                    <td>
                                        @if (deal.Status == 5)
                                        {
                                            <button type="button" class="btn btn-success btn-xs">Success</button>
                                        }
                                        else if (deal.Status == 4)
                                        {
                                            <button type="button" class="btn btn-danger btn-xs">Lost</button>
                                        }
                                        else if (deal.Status == 1)
                                        {
                                            <button type="button" class="btn btn-primary btn-xs">Active</button>
                                        }

                                        else if (deal.Status == 3)
                                        {
                                            <button type="button" class="btn btn-primary btn-xs">Waiting Order</button>
                                        }
                                        else if (deal.Status == 2)
                                        {
                                            <button type="button" class="btn btn-warning btn-xs">On Hold</button>
                                        }
                                    </td>
                                    <td>
                                        <a href="/Deal/Detail?id=@deal.id" class="btn btn-primary btn-xs"><i class="fa fa-folder"></i> View </a>
    
                                        <a href="#" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i> Delete </a>
                                    </td>
                                </tr>
                            }
                            
               
                        </tbody>
                    </table>
                    <!-- end project list -->
                </div>
            </div>
        </div>
    </div>

TEMP/Views/Deal/temp.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset='UTF-8'>

    <title>Progress Bars</title>


    <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
    <style>
		.meter {
			height: 20px;  /* Can be anything */
			position: relative;
			margin: 60px 0 20px 0; /* Just for demo spacing */
			background: #555;
			-moz-border-radius: 25px;
			-webkit-border-radius: 25px;
			border-radius: 25px;
			padding: 10px;
			-webkit-box-shadow: inset 0 -1px 1px rgba(255,255,255,0.3);
			-moz-box-shadow   : inset 0 -1px 1px rgba(255,255,255,0.3);
			box-shadow        : inset 0 -1px 1px rgba(255,255,255,0.3);
		}
		.meter > span {
			display: block;
			height: 100%;
			   -webkit-border-top-right-radius: 8px;
			-webkit-border-bottom-right-radius: 8px;
			       -moz-border-radius-topright: 8px;
			    -moz-border-radius-bottomright: 8px;
			           border-top-right-radius: 8px;
			        border-bottom-right-radius: 8px;
			    -webkit-border-top-left-radius: 20px;
			 -webkit-border-bottom-left-radius: 20px;
			        -moz-border-radius-topleft: 20px;
			     -moz-border-radius-bottomleft: 20px;
			            border-top-left-radius: 20px;
			         border-bottom-left-radius: 20px;
			background-color: rgb(43,194,83);
			background-image: -webkit-gradient(
			  linear,
			  left bottom,
			  left top,
			  color-stop(0, rgb(43,194,83)),
			  color-stop(1, rgb(84,240,84))
			 );
			background-image: -moz-linear-gradient(
			  center bottom,
			  rgb(43,194,83) 37%,
			  rgb(84,240,84) 69%
			 );
			-webkit-box-shadow:
			  inset 0 2px 9px  rgba(255,255,255,0.3),
			  inset 0 -2px 6px rgba(0,0,0,0.4);
			-moz-box-shadow:
			  inset 0 2px 9px  rgba(255,255,255,0.3),
			  inset 0 -2px 6px rgba(0,0,0,0.4);
			box-shadow:
			  inset 0 2px 9px  rgba(255,255,255,0.3),
			  inset 0 -2px 6px rgba(0,0,0,0.4);
			position: relative;
			overflow: hidden;
		}
		.meter > span:after, .animate > span > span {
			content: "";
			position: absolute;
			top: 0; left: 0; bottom: 0; right: 0;
			background-image:
			   -webkit-gradient(linear, 0 0, 100% 100%,
			      color-stop(.25, rgba(255, 255, 255, .2)),
			      color-stop(.25, transparent), color-stop(.5, transparent),
			      color-stop(.5, rgba(255, 255, 255, .2)),
			      color-stop(.75, rgba(255, 255, 255, .2)),
			      color-stop(.75, transparent), to(transparent)
			   );
			background-image:
				-moz-linear-gradient(
				  -45deg,
			      rgba(255, 255, 255, .2) 25%,
			      transparent 25%,
			      transparent 50%,
			      rgba(255, 255, 255, .2) 50%,
			      rgba(255, 255, 255, .2) 75%,
			      transparent 75%,
			      transparent
			   );
			z-index: 1;
			-webkit-background-size: 50px 50px;
			-moz-background-size: 50px 50px;
			-webkit-animation: increasebar  2s linear infinite;
			   -webkit-border-top-right-radius: 8px;
			-webkit-border-bottom-right-radius: 8px;
			       -moz-border-radius-topright: 8px;
			    -moz-border-radius-bottomright: 8px;
			           border-top-right-radius: 8px;
			        border-bottom-right-radius: 8px;
			    -webkit-border-top-left-radius: 20px;
			 -webkit-border-bottom-left-radius: 20px;
			        -moz-border-radius-topleft: 20px;
			     -moz-border-radius-bottomleft: 20px;
			            border-top-left-radius: 20px;
			         border-bottom-left-radius: 20px;
			overflow: hidden;
		}
        .myspan {
        content: "";
			position: absolute;
			top: 0; left: 0; bottom: 0; right: 0;
			background-image:
			   -webkit-gradient(linear, 0 0, 100% 100%,
			      color-stop(.25, rgba(255, 255, 255, .2)),
			      color-stop(.25, transparent), color-stop(.5, transparent),
			      color-stop(.5, rgba(255, 255, 255, .2)),
			      color-stop(.75, rgba(255, 255, 255, .2)),
			      color-stop(.75, transparent), to(transparent)
			   );
			background-image:
				-moz-linear-gradient(
				  -45deg,
			      rgba(255, 255, 255, .2) 25%,
			      transparent 25%,
			      transparent 50%,
			      rgba(255, 255, 255, .2) 50%,
			      rgba(255, 255, 255, .2) 75%,
			      transparent 75%,
			      transparent
			   );
			z-index: 1;
			-webkit-background-size: 50px 50px;
			-moz-background-size: 50px 50px;
			-webkit-animation: increasebar  2s linear infinite;
			   -webkit-border-top-right-radius: 8px;
			-webkit-border-bottom-right-radius: 8px;
			       -moz-border-radius-topright: 8px;
			    -moz-border-radius-bottomright: 8px;
			           border-top-right-radius: 8px;
			        border-bottom-right-radius: 8px;
			    -webkit-border-top-left-radius: 20px;
			 -webkit-border-bottom-left-radius: 20px;
			        -moz-border-radius-topleft: 20px;
			     -moz-border-radius-bottomleft: 20px;
			            border-top-left-radius: 20px;
			         border-bottom-left-radius: 20px;
			overflow: hidden;
        
        }
		.animate > span:after {
			display: none;
		}

		@@-webkit-keyframes increasebar  {
		    0% {
		       background-position: 0 0;
		    }
		    100% {
		       background-position: 50px 50px;
		    }
		}

		.orange > span {
			background-color: #f1a165;
			background-image: -moz-linear-gradient(top, #f1a165, #f36d0a);
			background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #f1a165),color-stop(1, #f36d0a));
			background-image: -webkit-linear-gradient(#f1a165, #f36d0a);
		}

		.red > span {
			background-color: #f0a3a3;
			background-image: -moz-linear-gradient(top, #f0a3a3, #f42323);
			background-image: -webkit-gradient(linear,left top,left bottom,color-stop(0, #f0a3a3),color-stop(1, #f42323));
			background-image: -webkit-linear-gradient(#f0a3a3, #f42323);
		}

		.nostripes > span > span, .nostripes > span:after {
			-webkit-animation: none;
			background-image: none;
		}
    </style>
</head>
<body>


    <h1>Progress Bars</h1>


    <div class="meter">
        <span style="width: 25%"></span>
    </div>


    <div class="meter orange nostripes">
        <span style="width: 33.3%"></span>
    </div>


    <div class="meter red">
        <span style="width: 80%"></span>
    </div>

    <div class="meter animate">
        <span  style="width: 50%"><span class="myspan"></span></span>
    </div>



</body>
</html>